### ISSUE TITLE
Unable to handle an exception

### ISSUE THREAD

**Issue by arikgelman** [CiscoDevNet/uniq#43]
I am getting this error and I unable to handle the exception, even if I put the operation under try and except.

Error:

```
Error Code: 404 URL:https://sandboxapic.cisco.com/api/v1/interface/network-device/17184480-2617-42c3-b267-4fade5f794a9 Data:{} Headers:{'X-Auth-Token': 'ST-4896-fVSZ1kDWAu0aKwnJtfcb-cas', 'Cookie': 'JSESSIONID=4DFF3F3BAC4B9E8C1F4F1B026DE4821F; Path=/apic-em-inventory-manager-service/; HttpOnly; Secure', 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-CSRF-Token': 'soon-enabled'} Message:{"response":{"errorCode":"Not found","message":"Request data not found","detail":"No resource found with deviceId: 17184480-2617-42c3-b267-4fade5f794a9"},"version":"1.0"}
Traceback (most recent call last):
  File "C:\Python35-32\lib\site-packages\uniq\apis\client_manager.py", line 187, in call_api
    response.raise_for_status()
  File "C:\Python35-32\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sandboxapic.cisco.com/api/v1/interface/network-device/17184480-2617-42c3-b267-4fade5f794a9
```

Code:

```
from uniq.apis.nb.client_manager import NbClientManager

apicEmServer = NbClientManager(server="sandboxapic.cisco.com",
                                 username="devnetuser",
                                 password="Cisco123!",
                                 connect=True)

allNetworkDevices = []
allInterfaces = {}
try:
    allNetworkDevices = apicEmServer.networkdevice.getAllNetworkDevice()
    allNetworkDevices = apicEmServer.serialize(allNetworkDevices)
except:
    print("Error") 
if allNetworkDevices is not None:
    for networkDevice in range(len(allNetworkDevices['response'])):

        try:
            deviceInterfaces = apicEmServer.interface.getInterfaceByDeviceId(deviceId = allNetworkDevices['response'][networkDevice]['id'])
            deviceInterfaces = apicEmServer.serialize(deviceInterfaces)
            print(allNetworkDevices['response'][networkDevice]['id'])

            if deviceInterfaces is not None:
                for line in range(len(deviceInterfaces['response'])):
                    if deviceInterfaces['response'][line]['description'] != "" and deviceInterfaces['response'][line]['description'] is not None:
                        allInterfaces[deviceInterfaces['response'][line]['description']] = allNetworkDevices['response'][networkDevice]['hostname'], allNetworkDevices['response'][networkDevice]['managementIpAddress'], deviceInterfaces['response'][line]['portName']
        except:
            print("Unable to get interface information from " + allNetworkDevices['response'][networkDevice]['id'])
print(allInterfaces)`
```

**Comment by ameyspatil** [comment]
I just ran your code verbatim, and it works perfectly fine, this is the output.

```
2dc30cac-072e-4d67-9720-cc302d02695a
Unable to get interface information from 17184480-2617-42c3-b267-4fade5f794a9
3ab14801-5c88-477d-bbb5-0aca5e5ba840
80036c7d-c82e-412c-ac01-b05f9badfcba
Unable to get interface information from 80036c7d-c82e-412c-ac01-b05f9badfcba
bc14ad0c-197b-476c-b9f9-10758879b4e4
Unable to get interface information from bc14ad0c-197b-476c-b9f9-10758879b4e4
24ac6aa8-7759-44d5-90a3-00c83e96583d
1a167f1a-feac-4ff1-8f70-9e20af22d99b
ed8dbe19-5dd0-48e4-a40f-c8787f1d93a5
8d32f709-cbcf-4c9b-99eb-ee6aabde8e74
554477e0-46ac-47bb-990e-4e20f0450e6f
d23ba4fb-cfe8-465b-be23-a9b0d89ce898
93ad4feb-5d17-4999-b46d-387f69113fc3
5a3bdb62-5def-40a1-be98-944ba2a7d863
Unable to get interface information from 5a3bdb62-5def-40a1-be98-944ba2a7d863
{' Connected to CAMPUS-CORE1': ('CAMPUS-Dist1', '55.1.1.100', 'GigabitEthernet5/7'), ' Connected to CAMPUS-Access1': ('CAMPUS-Dist1', '55.1.1.100', 'GigabitEthernet5/5'), ' Connected to Dist1': ('CAMPUS-Access1', '212.1.10.1', 'GigabitEthernet1/0/1'), ' Connected to Uplink Router': ('AHEC-2960C1', '165.10.1.31', 'FastEthernet0/1'), ' Connected to WLC5508': ('CAMPUS-Dist1', '55.1.1.100', 'GigabitEthernet5/38'), ' Connected to CAMPUS-DIST2': ('CAMPUS-Dist1', '55.1.1.100', 'GigabitEthernet5/48'), 'Unit: 0 Slot: 0 Port: 4 Gigabit - Level 0x6070001': ('Campus-WLC-5508', '55.1.1.2', 'GigabitEthernet0/0/4'), ' Connected to PnP Demo Switch': ('Branch2-Router.yourdomain.com', '218.1.100.100', 'GigabitEthernet0/0'), ' To CAMPUS-Core2': ('CAMPUS-Core1', '211.1.1.1', 'GigabitEthernet3/47'), ' #WAN#100M#SPP1#': ('CAMPUS-Router2', '210.2.2.1', 'GigabitEthernet0/0/3'), ' Connected to Wireless AP': ('CAMPUS-Access1', '212.1.10.1', 'GigabitEthernet1/0/26'), ' To CAMPUS-Core1': ('CAMPUS-Core2', '211.2.2.1', 'GigabitEthernet3/47')}
```

**Comment by ameyspatil** [comment]
Actually you are handling the exception, that is the reason the code proceeds to display the interface information for other network devices.

This is the response I see:

```
2dc30cac-072e-4d67-9720-cc302d02695a
Error Code: 404 URL:https://sandboxapic.cisco.com/api/v1/interface/network-device/17184480-2617-42c3-b267-4fade5f794a9 Data:{} Headers:{'Accept': 'application/json', 'X-Auth-Token': 'ST-5937-EdyBXOysZOt0vdmwFtwa-cas', 'Content-Type': 'application/json', 'Cookie': 'JSESSIONID=00A28CF92507CFD916686E31865F026B; Path=/apic-em-inventory-manager-service/; HttpOnly; Secure', 'X-CSRF-Token': 'soon-enabled'} Message:{"response":{"errorCode":"Not found","message":"Request data not found","detail":"No resource found with deviceId: 17184480-2617-42c3-b267-4fade5f794a9"},"version":"1.0"}
Traceback (most recent call last):
  File "/Users/amepatil/.virtualenvs/uniq_github_package_installed/lib/python3.5/site-packages/uniq/apis/client_manager.py", line 187, in call_api
    response.raise_for_status()
  File "/Users/amepatil/.virtualenvs/uniq_github_package_installed/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sandboxapic.cisco.com/api/v1/interface/network-device/17184480-2617-42c3-b267-4fade5f794a9
Unable to get interface information from 17184480-2617-42c3-b267-4fade5f794a9
3ab14801-5c88-477d-bbb5-0aca5e5ba840
```

The following line is printed after the error message
Unable to get interface information from **17184480-2617-42c3-b267-4fade5f794a9**

**Comment by arikgelman** [comment]
Thank you very much for the fast response, This means I will see the error no matter what ?

**Comment by ameyspatil** [comment]
To give more context, that exception is getting logged as part of 
https://github.com/CiscoDevNet/uniq/blob/master/apis/client_manager.py#L189

Also, for why the other print messages that are not preceded by the same exception, that could be due to the script failing for some other reason (may be a `KeyError` or `IndexError`) in these lines:

```
deviceInterfaces = apicEmServer.serialize(deviceInterfaces)
            print(allNetworkDevices['response'][networkDevice]['id'])

            if deviceInterfaces is not None:
                for line in range(len(deviceInterfaces['response'])):
                    if deviceInterfaces['response'][line]['description'] != "" and deviceInterfaces['response'][line]['description'] is not None:
                        allInterfaces[deviceInterfaces['response'][line]['description']] = allNetworkDevices['response'][networkDevice]['hostname'], allNetworkDevices['response'][networkDevice]['managementIpAddress'], deviceInterfaces['response'][line]['portName']

```

The recommended practice is to have a smaller block (ideally a single line) between an all encapsulating try and except.
Something like this:

```
        try:
            deviceInterfaces = apicEmServer.interface.getInterfaceByDeviceId(deviceId = allNetworkDevices['response'][networkDevice]['id'])
        except:
            print("Different EXCEPTION \n")    

        try:
            deviceInterfaces = apicEmServer.serialize(deviceInterfaces)
            print(allNetworkDevices['response'][networkDevice]['id'])
```

or make the except catch a specific exception like so:

```
from requests.exceptions import HTTPError
.
.
 except HTTPError as e:
            print("Unable to get interface information from "
```

Another recommendation is to always print/log the Exception itself

```
except HTTPError as e:
            print(e)

except Exception as e:
            print(e)
```

**Comment by arikgelman** [comment]
Thank you! I will work on it.

**Comment by ameyspatil** [comment]
All information that this library logs is done through python's logging module.
We have defined a logger named `uniq`

So in case you do not want to see that log message, you can do some thing like so:

```
import logging
logger = logging.getLogger("uniq")
logger.disabled = True
```

**Comment by ameyspatil** [comment]
Closing as not an issue.
